config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'landing_page/show'
  root to: 'landing_page#show'
  
  resources :rides
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    ## rider logic // admin roles
    # if user.admin?
      
      
      
    # else
      
    #   can :update, Ride do |ride|
    #     ride.user == user
    #   end
      
    #   can :destroy, Ride do |ride|
    #     ride.user == user
    #   end
      
    #   can :create, Ride
    #   can 
      
    # end
    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
    enum status: [:pending, :allocated, :in_progress, :complete, :cancelled]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def show
    if current_user
      redirect_to rides_path
    end
    
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
      
    before_action :authenticate_user!
    before_action :find_ride, only: [:edit, :update, :destroy]
  
  def index
    @rides = Ride.all
  end

  def edit
   
  end
  
  def update
    # byebug
    # ride_params = ride_params.merge({ status: params[:ride][:status]})
    @rides.update(ride_params)
    redirect_to rides_path
  end

  def new
    @rides = Ride.new
  end
  
  def create
    
    @rides = Ride.new(ride_params)
    if @rides.save
      redirect_to rides_path
    else
      render 'new'
    end
  end
  
  private 
  
  def find_ride
    @rides = Ride.find(params[:id])
  end
  
  def ride_params
    params.require(:ride).permit(
      :status,
      :pickup_pt,
      :destination_pt,
      :driver,
      :rider,
      :coupon,
      :fare,
      :item_description,
      :max_dimensions,
      :max_weight,
      :help_needed,
      :start_time,
      :end_time,
      :need_insurance,
      :item_photo)
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/landing_page/show.html.erb
<%= link_to "login", new_user_session_path %>
<h1>LandingPage#show</h1>
<p>Find me in app/views/landing_page/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if current_user %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/rides/_form.html.erb
<%= form_for @rides do |r| %>

<%= r.label :status %><br>
<%= r.select :status, Ride.statuses.map { |key, value| [key.humanize, key] } %>

<%= r.label :pickup_pt %>
<%= r.text_field :pickup_pt %>

<%= r.label :destination_pt %>
<%= r.text_field :destination_pt %>

<%= r.label :driver %>
<%= r.text_field :driver %>

<%= r.label :rider %>
<%= r.text_field :rider %>

<%= r.label :coupon %>
<%= r.text_field :coupon %>

<%= r.label :fare %>
<%= r.text_field :fare %>

<%= r.label :item_description %>
<%= r.text_field :item_description %>

<%= r.label :max_dimensions %>
<%= r.text_field :max_dimensions %>

<%= r.label :max_weight %>
<%= r.text_field :max_weight %>

<%= r.label :help_needed %>
<%= r.check_box :help_needed %>

<%= r.label :start_time %>
<%= r.text_field :start_time %>

<%= r.label :end_time %>
<%= r.text_field :end_time %>

<%= r.label :need_insurance %>
<%= r.check_box :need_insurance %>

<%= r.label :item_photo %>
<%= r.text_field :item_photo %>

<%= r.submit %>
 
<% end %>

app/views/rides/edit.html.erb
<h1>Rides#edit</h1>
<p>Find me in app/views/rides/edit.html.erb</p>

<%= render 'form'%>

app/views/rides/index.html.erb
<h1>Rides#index</h1>
<p>Find me in app/views/rides/index.html.erb</p>

<table>
    <th>status</th>
    <th>pickup_pt</th>
    <th>destination_pt</th>
    <th>driver</th>
    <th>rider</th>
    <th>coupon</th>
    <th>fare</th>
    <th>item_description</th>
    <th>max_dimensions</th>
    <th>max_weight</th>
    <th>help_needed</th>
    <th>start_time</th>
    <th>end_time</th>
    <th>need_insurance</th>
    <th>item_photo</th>

    
    <% @rides.each do |r| %>
    <tr>
    <td><%= r.status %></td>
    <td><%= r.pickup_pt %></td>
    <td><%= r.destination_pt %></td>
    <td><%= r.driver %></td>
    <td><%= r.rider %></td>
    <td><%= r.coupon %></td>
    <td><%= r.fare %></td>
    <td><%= r.item_description %></td>
    <td><%= r.max_dimensions %></td>
    <td><%= r.max_weight %></td>
    <td><%= r.help_needed %></td>
    <td><%= r.start_time %></td>
    <td><%= r.end_time %></td>
    <td><%= r.need_insurance %></td>
    <td><%= r.item_photo %></td>
    <td><%= link_to 'edit', edit_ride_path(r) %></td>
    </tr>

<% end %>
</table>  

<td><%= link_to 'new', new_ride_path %></td>

app/views/rides/new.html.erb
<h1>Rides#new</h1>
<p>Find me in app/views/rides/new.html.erb</p>

<%= render 'form'%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>